Aufnahmepunkte_Solling_ph2 <- read.delim("D:/Masterarbeit_R/Daten/Zwischen_Daten/Betriebsinventur_R/Aufnahmepunkte_Solling_ph2.txt", header = TRUE, sep = ";")
Aufnahmepunkte_vorr <- read.delim("D:/Masterarbeit_R/Daten/Zwischen_Daten/Betriebsinventur_R/Aufnahmepunkte_vorr.txt", header = TRUE, sep = ";")
Punkte_mit_Genauigkeit <- read.delim("D:/Masterarbeit_R/Daten/Zwischen_Daten/Betriebsinventur_R/Punkte_mit_Genauigkeit.txt", header = TRUE, sep = ";")
Soll_Ist_Vergleich <- read.delim("D:/Masterarbeit_R/Daten/Zwischen_Daten/Betriebsinventur_R/Soll_Ist_Vergleich.txt", header = TRUE, sep = ";")
tblDatPh1_ZE <- read.delim("D:/Masterarbeit_R/Daten/Zwischen_Daten/Betriebsinventur_R/tblDatPh1_ZE.txt", header = TRUE, sep = ";")
tblDatPh2_Vorr_ZE <- read.delim("D:/Masterarbeit_R/Daten/Zwischen_Daten/Betriebsinventur_R/tblDatPh2_Vorr_ZE.txt", header = TRUE, sep = ";")
tblDatPh2_ZE <- read.delim("D:/Masterarbeit_R/Daten/Zwischen_Daten/Betriebsinventur_R/tblDatPh2_ZE.txt", header = TRUE, sep = ";")

structure(Aufnahmepunkte_Solling_ph2)
structure(Aufnahmepunkte_vorr)
structure(Punkte_mit_Genauigkeit)
structure(Soll_Ist_Vergleich)
structure(tblDatPh1_ZE)
structure(tblDatPh2_Vorr_ZE)
structure(tblDatPh2_ZE)

summary(Aufnahmepunkte_Solling_ph2)
summary(Aufnahmepunkte_vorr)
summary(Punkte_mit_Genauigkeit)
summary(Soll_Ist_Vergleich)
summary(tblDatPh1_ZE)
summary(tblDatPh2_Vorr_ZE)
summary(tblDatPh2_ZE)

#table()
table(Aufnahmepunkte_Solling_ph2$DatPh2_FA)
names(Aufnahmepunkte_Solling_ph2)[names(Aufnahmepunkte_Solling_ph2) == "DatPh2_FA"] <- "Forstamt"
table(Aufnahmepunkte_Solling_ph2$Forstamt)
